Añadido efecto de sangre
NestorTejero/ES2016A pull request #186
Opened 2016-12-07 14:19 UTC by eslizon13

Se ha creado la sangre, no realiza loop, se utiliza una vez.
Falta ver como posicionarlo delante de un enemigo cuando es golpeado.

2016-12-07 14:28 UTC, eslizon13 commented
No aparece una vez realizado el pull request. Tengo que volverlo a mirar.
Solo se han creado el material y la textura, pero la particula no.

2016-12-07 14:37 UTC, Nerucius commented
**Sugerencia para que aparezca en un enemigo al morir o ser atacado:**
- Convertir el efecto en un prefab, dentro de la carpeta Resources
- Asociar el prefab a una variable GameObject de EnemyBehavior, con nombre `deathEffect` o algo parecido
- En el metodo `SelfDestroy()` o 'TakeDamage()` de `EnemyBehavior`:
`
GameObject effect = Instantiate(deathEffect, transform.position + Vector3.up, Quaternion.identity) as GameObject;
`

2016-12-07 22:41 UTC, sdiaz7 commented
Como dice @Nerucius , intenta crear un prefab con el efecto para que se pueda mostrar desde el script de EnemyBehavior. Si no sabes muy bien como hacerlo los programadores podemos ayudarte.

2016-12-08 15:40 UTC, sdiaz7 requested changes
La textura nos gusta, pero como dice @Nerucius , intenta crear un prefab con el efecto para que se pueda mostrar desde el script de EnemyBehavior, así no tendremos que abrir tantas ramas e issues. Si no sabes muy bien como hacerlo los programadores podemos ayudarte.

2016-12-10 13:38 UTC, sdiaz7 commented
Tal como quedamos, he subido la integración del Hit prefab en el EnemyBehavior. He aumentado un poco el tamaño del prefab para que pueda apreciarse mejor el efecto. El objeto hit se instancia en la misma posición del proyectil (es decir, en el punto de impacto) y usa la misma dirección y sentido que este para propagarse. El objeto se autodestruye pasado 1 segundo.

Mirad a ver que os parece el resultado.

2016-12-10 13:51 UTC, eslizon13 commented
Me gusta tal como está, Pull Request y queda pendiente de aprovación.

2016-12-10 13:54 UTC, sdiaz7 approved these changes

2016-12-10 14:07 UTC, merged