create a new enemy, design and texture and name convention
NestorTejero/ES2016A pull request #210
Opened 2016-12-11 20:51 UTC by charlyhook

![capturakid](https://cloud.githubusercontent.com/assets/11389074/21083214/fc654c54-bfeb-11e6-9593-485592080e75.PNG)

2016-12-11 22:34 UTC, sgarriga10 reviewed
Revisión relaizada en Blender. Se ve correctamente tal y como muestro a continuación en la fotografía. 

La animación también se puede ver correctamente.

No la apruebo a la espera de que se pruebe integrada en unity.

Revisión en Blender correcta.

![capturakidreview](https://cloud.githubusercontent.com/assets/11062710/21083902/5e6200ce-bffa-11e6-8c14-27ddb1c25fca.PNG)

2016-12-12 18:14 UTC, sdiaz7 requested changes
El modelo está bien orientado, pero las animaciones están mal etiquetadas:

![image](https://cloud.githubusercontent.com/assets/17719241/21110660/5ac484c4-c09e-11e6-8086-6fe2c8356bce.png)

Cambiad los nombres para que nos sea más fácil distinguir cual es cual.
Siguiendo con las animaciones, he observado que con una de las animaciones el modelo anda, suelta la lanza y se mueve de manera extraña. Si puedo subiré un vídeo para que se entienda mejor lo que intento decir, de momento añado una foto:

![image](https://cloud.githubusercontent.com/assets/17719241/21110604/1db8c5c2-c09e-11e6-8091-b8c70f4d15f7.png)

Revisad la animación, porque tal como está ahora no puedo dar mi aprobación.

PD: No hace falta que subáis los lamp, pero lo que sí nos vendría bien es el mapa de normales

2016-12-12 19:00 UTC, sdiaz7 commented
[![](https://img.youtube.com/vi/5ktFSCYQWsg/0.jpg)](https://www.youtube.com/watch?v=5ktFSCYQWsg "Click to play on Youtube.com")

2016-12-13 17:00 UTC, charlyhook commented
Cierro el PR porque no me da tiempo de acabar.

Dejo para el siguiente sprint arreglar la animación.

2016-12-13 17:00 UTC, closed without merging