Blood textures added
NestorTejero/ES2016A pull request #216
Opened 2016-12-11 22:00 UTC by sgarriga10

He subido dos texturas de sangre, para emular diferentes daños a los enemigos.

![Uploading texturaSangre1.jpg…]()
![texturasangre2](https://cloud.githubusercontent.com/assets/11062710/21083660/a80b8da8-bff5-11e6-8873-38d5f13f21d9.png)

2016-12-11 22:23 UTC, carlosarenasf submitted a review, later dismissed
No hay código que revisar, las imágenes son correctas

2016-12-12 11:22 UTC, Nerucius requested changes
Dos problemas con las texturas:
- Han de tener dimensiones de altura x anchura que sean potencias de 2<sup>n</sup> (i.e. 128x128, 512x512...)
- Para que podamos usarlas en el juego tienen que tener los bordes transparentes, sino se veran como "cuadrados" en el suelo. Piensa mas bien en una mancha de pintura roja que en un cuadro satánico.

Ejemplo del half life
![Imagen](http://files.gamebanana.com/img/ss/sprites/159.jpg)

2016-12-12 18:47 UTC, sgarriga10 commented
@Nerucius Las imágenes de sangre no definimos como deberían ser. De todas formas he añadido 4 imágenes nuevas en otro commit que cumplen esos requisitos (espero). Revisalo si puedes. Gracias.

Dejo las 4 imágenes a continuación:

![textura-sangre2](https://cloud.githubusercontent.com/assets/11062710/21111873/ce224eb0-c0a3-11e6-934c-2b7d7a43a451.png)
![textura-sangre3](https://cloud.githubusercontent.com/assets/11062710/21111874/ce24118c-c0a3-11e6-9487-6a5087ed1ed6.png)
![textura-sangre4](https://cloud.githubusercontent.com/assets/11062710/21111872/ce2214c2-c0a3-11e6-88fa-040972e4d47c.png)
![textura-sangre](https://cloud.githubusercontent.com/assets/11062710/21111875/ce263016-c0a3-11e6-9ebb-f0479d8f1531.png)

2016-12-12 20:52 UTC, Nerucius commented
Ya por pedir, podria ser que las texturas no estuvieran aplastadas y que no se cortará en los bordes?

2016-12-12 21:27 UTC, sgarriga10 commented
Podría ser pero para el siguiente sprint @Nerucius.

2016-12-13 17:01 UTC, sgarriga10 commented
@Nerucius Os valen las texturas para este sprint o cierro el PR y lo dejamos para el siguiente sprint?

2016-12-13 17:09 UTC, Nerucius commented
No me da tiempo implementarlo para este, Sera mejor que paseis la issue al siguiente sprint y redefinais la DoD @sgarriga10

2016-12-14 21:05 UTC, closed without merging