Logic for Columbus tower's appearance changing when damaged
NestorTejero/ES2016A pull request #251
Opened 2016-12-16 11:59 UTC by sdiaz7

See issue #172 for implementation details.

Basically, the redefined HomeBehavior allows for N meshes to be assigned to the prefab through the Inspector (variable named threshold Meshes). The script then defines N damage thesholds, and changes home's mesh once a threshold is reached. I've decided to work with meshes rather than objects because it's much more simplier provided all the meshes are about the same size. 
Changing the mesh does not change the material. If that proves to be a problem, material can be changed just as easily as mesh.

**Recommendations for testing:**
- Columbus tower's mesh is much more bigger than most game meshes. Since Home's scale keeps the same after changing the mesh, some meshes might look very tiny when placed.  I recommend using Unity native meshes (Cube, Sphere, etc...), those look small but visible.
- I also recommend to lower both health and MAXIMUM HEALTH, to about 10N being N the number of meshes.

2016-12-16 19:07 UTC, mgonzafe91 requested changes
Solo veo un pequeño fallo, modifica está linea:
![image](https://cloud.githubusercontent.com/assets/9026825/21274985/12fe228c-c3cb-11e6-8c65-d3ccde106ef4.png)

 borrando el -1 ya que sino en el último mesh siempre entra pero no lo modifica:
![image](https://cloud.githubusercontent.com/assets/9026825/21274921/cf087780-c3ca-11e6-9e8c-b92962c4e6be.png)

Edit: Si modifica el mesh pero lo modifica varias veces

2016-12-16 19:20 UTC, kazusaki1 commented
Sin el -1 he comprobado que pasa por todos los mesh:

![image](https://cloud.githubusercontent.com/assets/9026825/21275393/e721d5b2-c3cc-11e6-9ec3-e83c283495f9.png)

Así que con esa pequeña modificación por mi parte se puede integrar.

2016-12-16 19:25 UTC, sdiaz7 commented
Si, yo también acabo de comprobarlo. Acabo de subir el fix. Gracias por avisar!

2016-12-16 19:29 UTC, mgonzafe91 approved these changes

2016-12-16 19:29 UTC, kazusaki1 commented
Por mi parte como dije todo perfect, hago merge

2016-12-16 19:31 UTC, merged

2017-01-10 21:55 UTC, NestorTejero commented on Assets/Scripts/HomeBehavior.cs
> +                threshold = (int)Mathf.Min(threshold + 1, thresholdMeshes.Length);   // update threshold
comentari

2017-01-10 21:56 UTC, NestorTejero commented
@kazusaki1 veig que vas comentar:
> Solo veo un pequeño fallo, modifica está linea:

Saps que pots posar comentaris a les línes del codi directament? Vas al commit i allà escrius apretant el signe +. Acabo de fer la prova a https://github.com/NestorTejero/ES2016A/pull/251/commits/8d5ef99c209b0fe39e1f2c2a681ef27850a2129a