252 fixsettingsmenu
NestorTejero/ES2016A pull request #260
Opened 2016-12-16 18:42 UTC by sergirenom

* Settings icon of Pause Menu replaced
* Unnecessary mute buttons removed of Settings Menu

2016-12-16 19:51 UTC, mgonzafe91 requested changes
Parece que faltan cosas, mira de revisar que tengas la escena actualizada porque yo acabo de probarlo con lo de dev y añadiendo los 6 ficheros nuevos.

![image](https://cloud.githubusercontent.com/assets/9026825/21276347/3975ea84-c3d1-11e6-9237-e266aba18043.png)


![image](https://cloud.githubusercontent.com/assets/9026825/21276355/46469a4c-c3d1-11e6-85f5-13554a474e2a.png)

2016-12-16 19:54 UTC, kazusaki1 commented
Por cierto, procura subir una imagen de las modificaciones para poder comparar mejor si lo que nos muestra es el mismo resultado que a ti.

2016-12-16 21:29 UTC, kazusaki1 commented
Lo que falta es el Settings:

![image](https://cloud.githubusercontent.com/assets/9026825/21279159/241b08c8-c3df-11e6-8eac-f25fe9e6aa9b.png)

2016-12-19 09:54 UTC, sergirenom commented
Gracias por la revisión @kazusaki1 ! Ya está el title 
![es](https://cloud.githubusercontent.com/assets/11387984/21308242/5a0a82dc-c5d9-11e6-9a52-8afd1675c988.png)

2016-12-19 19:18 UTC, mgonzafe91 approved these changes

2016-12-19 19:19 UTC, kazusaki1 commented
Todo parece correcto así que lo apruebo

2016-12-19 19:20 UTC, merged