Corregir orientacion de porky
NestorTejero/ES2016A pull request #262
Opened 2016-12-16 21:39 UTC by vmganela

Definition of Done:
- Modelo orientado correctamente.
- El tamaño correcto
- Al exportar no se pierda nada(mirando que esten animaciones y demas)

![cerdo](https://cloud.githubusercontent.com/assets/6916126/21279314/ed027faa-c3df-11e6-9ca7-46de6a637718.png)

2016-12-16 22:46 UTC, sdiaz7 requested changes
Aún hay problemas con el jinete y la estructura de madera. ¿Puede ser que haya que rotarla a parte?

![image](https://cloud.githubusercontent.com/assets/17719241/21280976/d40e0d52-c3e9-11e6-97fb-27667ecb9ebe.png)

2016-12-17 08:35 UTC, vmganela commented
Hola, acabo de hacer un push.
Diria que solventa lo del jinete.
No soy capaz de verlo funcionando el juego.
En caso de que lo consiga pondre un comentario conforme si el jinete esta totalmente perfecto

2016-12-17 12:40 UTC, sdiaz7 commented
Ahora todo el modelo está bien orientado:
![image](https://cloud.githubusercontent.com/assets/17719241/21286773/76a7159a-c45d-11e6-94f4-4c6999abf26e.png)

Hay algo que sigue dándonos algunos quebraderos de cabeza, y es que el modelo no parece bien centrado. Paso algunas imágenes comparando con otros modelos de enemigo:

![image](https://cloud.githubusercontent.com/assets/17719241/21286799/fb167028-c45d-11e6-9171-400f94f72b4d.png)

![image](https://cloud.githubusercontent.com/assets/17719241/21286805/104114c6-c45e-11e6-9d40-fd15eacef90b.png)

Esto nos obliga a poner un componente de navegación que no esté centrado en el modelo y puede hacer algunas cosas extrañas. No sé como se arregla esto en Blender (o si puede hacerse) pero si el coste es muy grande lo dejaremos como está y a ver qué pasa.

2016-12-17 13:30 UTC, vmganela commented
Se como solventarlo darme un poco de tiempo y lo resubo el modelo

2016-12-17 14:29 UTC, vmganela commented
Modificado. 
Cerdo centrado  el punto central esta entre las 2 primeras patas.

2016-12-17 16:31 UTC, sdiaz7 commented
Gracias, esto nos facilitará las cosas! Tendremos que rehacer el prefab de enemy-porki, pero ya habíamos previsto una issue para ello. Apruebo los cambios y hago el merge.

2016-12-17 16:32 UTC, sdiaz7 approved these changes

2016-12-17 16:32 UTC, merged