Final boss
NestorTejero/ES2016A pull request #281
Opened 2016-12-18 23:43 UTC by aoflus

Jefe final del juego.
Cuenta con una textura y 2 animaciones, la de atacar y la de andar.

Issue del pull request:
* [#136](../issues/136) Create a final boss.

![imagen](https://cloud.githubusercontent.com/assets/11500214/21297623/ac725c3a-c583-11e6-87dc-4048e9f00d89.png)

2016-12-18 23:59 UTC, Nerucius requested changes
Tiene buena pinta, ya seria el summum si encima nos pones el FBX a huevo :)

2016-12-19 00:04 UTC, aoflus commented
añadido el FBX.

2016-12-19 10:16 UTC, ezendirak commented
Animaciones correctas (atacar y andar). Texturas correctas (aunque estan por defecto y las deberían montar desde unity pero todo se ve bien)

![image](https://cloud.githubusercontent.com/assets/17324835/21308974/8bf94032-c5dc-11e6-8b9b-ff756880f09d.png)

2016-12-19 17:55 UTC, sdiaz7 commented
No puedo hacer una review así que dejo comentado el problema que he visto.

El modelo no está centrado:
![image](https://cloud.githubusercontent.com/assets/17719241/21323111/59ae229c-c61c-11e6-9e1a-eb8e04ef5ec6.png)

2016-12-20 00:00 UTC, ezendirak commented
Modelo centrado en blender y unity.

![image](https://cloud.githubusercontent.com/assets/17324835/21333392/ab68af8e-c64f-11e6-9292-b92a001a2ab4.png)

2016-12-20 02:11 UTC, Nerucius commented
Tengo el prefab funcional 100% pero va como 2 metros por sobre del suelo, es una conducta normal?

2016-12-20 09:58 UTC, aoflus commented
No debería flotar, se tendría que bajar un poco el nivel del personaje. Se puede hacer desde unity o hay que hacerlo en blender?

2016-12-20 11:49 UTC, Nerucius commented
No podemos en unity, lo mas fácil es que lo hagas en blender

2016-12-20 19:23 UTC, aoflus commented
Ya he hecho los cambios en blender.

2016-12-21 00:21 UTC, Nerucius approved these changes

2016-12-21 00:22 UTC, Nerucius commented
### Review

Prefab integrado, el enemigo no vuela, todo OK

![boss](https://cloud.githubusercontent.com/assets/7935504/21373049/e793873c-c71b-11e6-88c7-016128fd2287.PNG)

2016-12-21 00:22 UTC, merged